import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Main from './components/Main'
import About from './components/About'
import Skill from './components/Skill'
import Proejcts from './components/Proejcts'
import Contact from './components/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Amit PortFolio',
  description: 'Generated by Amit',
}

export default function RootLayout({}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Main />
        <About/>
        <Skill/>
        <Proejcts/>
        <Contact/>
      </body>
    </html>
  )
}

